import {test,expect} from "@playwright/test";
test("sample friend lens, comparison filters and same-place meanings",async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto("/");await page.getByRole("button",{name:"利用者 A で始める"}).click();await page.getByRole("button",{name:"つながる",exact:true}).click();await expect(page.getByRole("heading",{name:"みんなの地図",exact:true})).toBeVisible();await expect(page.locator(".lens-friend-card")).toHaveCount(4);await page.screenshot({path:".local/everyone-home.png"});
 await page.getByLabel("友人の地図を検索").fill("Kaito");await expect(page.locator(".lens-friend-card")).toHaveCount(1);await page.getByRole("button",{name:"地図を訪れる"}).click();await expect(page.locator(".lens-map")).toHaveAttribute("data-pin-count","5");await page.getByRole("button",{name:/Kaito Lens ON/}).click();await expect(page.locator(".lens-map")).toHaveAttribute("data-pin-count","4");await page.getByRole("button",{name:/あなたのレンズ/}).click();await page.screenshot({path:".local/everyone-friend.png"});
 await page.getByRole("button",{name:"自分の地図と比べる"}).click();await expect(page.locator(".lens-ring")).toContainText("50");await expect(page.locator(".lens-map")).toHaveAttribute("data-pin-count","3");await page.getByRole("tab",{name:"あなたのみ"}).click();await expect(page.locator(".lens-map")).toHaveAttribute("data-pin-count","1");await page.getByRole("tab",{name:"Kaitoのみ"}).click();await expect(page.locator(".lens-map")).toHaveAttribute("data-pin-count","2");await page.getByRole("tab",{name:"共通",exact:true}).click();await page.getByRole("button",{name:"本山",exact:true}).click();await expect(page.locator(".lens-ring")).toContainText("67");await page.getByRole("button",{name:"栄",exact:true}).click();await expect(page.getByText("この条件に該当する場所はありません。")).toBeVisible();await page.getByRole("button",{name:"すべて",exact:true}).click();
 await page.route("**/api/everyone",r=>r.fulfill({json:{common:"テスト用AI解釈：共通のカフェがあります。",difference:"テスト用AI解釈：平均滞在時間が異なります。",discovery:"テスト用AI解釈：異なる過ごし方です。"}}));await page.getByRole("button",{name:"AIで共通点と違いを読み解く"}).click();await expect(page.getByRole("heading",{name:"AIの解釈"})).toBeVisible();await page.screenshot({path:".local/everyone-compare.png",fullPage:true});
 await page.locator(".lens-selected-places").getByRole("button",{name:"本山の喫茶店"}).click();await expect(page.locator(".lens-meaning-columns")).toContainText("平均 91分");await expect(page.locator(".lens-meaning-columns")).toContainText("平均 48分");await expect(page.getByText("「友人と朝食を食べる場所」")).toBeVisible();await page.screenshot({path:".local/everyone-place.png"});await page.getByRole("button",{name:"みんなの地図で戻る"}).click();await expect(page.getByRole("heading",{name:"あなた × Kaito"})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(page.getByRole("navigation",{name:"ホームナビゲーション"}).getByRole("button")).toHaveCount(4);
});
test("comparison AI requires session, same origin and a known sample friend",async({request})=>{
 expect((await request.post("/api/everyone",{data:{friendId:"kaito"}})).status()).toBe(403);
 await request.post("/api/v1/session",{data:{actor:"A"}});
 expect((await request.post("/api/everyone",{data:{friendId:"private-user"}})).status()).toBe(400);
 expect((await request.post("/api/everyone",{headers:{origin:"https://example.com"},data:{friendId:"kaito"}})).status()).toBe(403);
});
