import {test,expect} from "@playwright/test";
test("history empty state and unchanged shared navigation",async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto("/");await page.getByRole("button",{name:"利用者 B で始める"}).click();await page.getByRole("button",{name:"地図を育てる",exact:true}).click();await page.getByRole("button",{name:"これまでの軌跡",exact:true}).click();await expect(page).toHaveURL(/#history$/);await expect(page.getByRole("heading",{name:"まだ、軌跡がありません"})).toBeVisible();await expect(page.getByRole("navigation",{name:"ホームナビゲーション"}).getByRole("button")).toHaveCount(4);await page.screenshot({path:".local/history-empty-mobile.png"});await page.getByRole("button",{name:"地図を開く",exact:true}).click();await expect(page).toHaveURL(/#explore$/);
});
test("history replays months, opens a numbered day and recaps genuine records",async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto("/");await page.getByRole("button",{name:"利用者 A で始める"}).click();
 await expect(page.getByRole("button",{name:"地図を育てる",exact:true})).toBeVisible();
 const nearby=await(await page.request.post("/api/places",{data:{lat:35.1688,lng:136.9089,radius:1000}})).json();
 for(const [index,at] of ["2026-08-03T01:00:00Z","2026-09-03T01:00:00Z","2026-09-03T03:00:00Z"].entries()){const r=await page.request.post("/api/personal",{data:{op:"visit",visit:{id:crypto.randomUUID(),placeId:nearby.places[index===2?1:0].id,enteredAt:at,durationMinutes:index===2?null:45,company:"unknown",weather:"unknown"}}});expect(r.ok()).toBe(true);}
 await page.getByRole("button",{name:"地図を育てる",exact:true}).click();await page.getByRole("button",{name:"これまでの軌跡",exact:true}).click();await expect(page.locator(".history-map")).toBeVisible();await page.getByLabel("履歴の月",{exact:true}).fill("2026-08");await expect(page.locator(".replay-controls strong")).toHaveText("2026-08");await expect(page.locator(".history-map")).toHaveAttribute("data-history-pins","1");await page.getByRole("button",{name:"リプレイを再生"}).click();await expect(page.getByLabel("履歴の月",{exact:true})).toHaveValue("2026-09");await expect(page.locator(".history-map")).toHaveAttribute("data-history-pins","2");await page.screenshot({path:".local/history-replay-mobile.png"});
 await page.getByRole("tab",{name:"Day",exact:true}).click();await page.getByLabel("履歴の日付",{exact:true}).fill("2026-09-03");await expect(page.locator(".journey-stop")).toHaveCount(2);await expect(page.getByText("滞在時間は未記録",{exact:true})).toBeVisible();await expect(page.locator(".history-route-note")).toContainText("実際に歩いた経路ではありません");await expect(page.locator(".history-map")).toHaveAttribute("data-rendered","true");await page.screenshot({path:".local/history-day-mobile.png"});
 await page.locator(".journey-stop").first().click();await expect(page.locator(".journey-stop").first()).toHaveAttribute("aria-expanded","true");await expect(page.locator(".journey-visit-details")).toContainText("到着");await page.getByRole("button",{name:"前の日",exact:true}).click();await expect(page.getByLabel("履歴の日付",{exact:true})).toHaveValue("2026-09-02");await expect(page.locator(".journey-stop")).toHaveCount(0);await page.getByRole("button",{name:"次の日",exact:true}).click();await expect(page.locator(".journey-stop")).toHaveCount(2);
 await page.getByRole("tab",{name:"Month",exact:true}).click();await expect(page.getByRole("heading",{name:"よく訪れたカテゴリ"})).toBeVisible();await expect(page.locator(".history-ranking")).toHaveCount(2);await expect(page.locator(".history-map")).toHaveAttribute("data-rendered","true");await page.screenshot({path:".local/history-month-mobile.png",fullPage:true});await page.getByRole("button",{name:/新しく見つけた場所/}).click();await expect(page.getByRole("tab",{name:"Replay",exact:true})).toHaveAttribute("aria-selected","true");await expect(page.getByLabel("この月に初めて訪れた場所だけ")).toBeChecked();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test("history rejects invalid dates and anonymous access",async({request})=>{
 expect((await request.get("/api/history?mode=month&period=2026-09")).status()).toBe(403);await request.post("/api/v1/session",{data:{actor:"B"}});expect((await request.get("/api/history?mode=day&period=2026-02-30")).status()).toBe(400);
});


