import {describe,it,expect} from "vitest";
import {mkdtempSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {HistoryStore} from "../src/infrastructure/history-store";
import {PersonalStore} from "../src/infrastructure/personal-store";
import {HistoryService} from "../src/server/history";
import {aggregateHistory,getDayJourney,getMonthlyHistorySummary,periodBounds,japanDay} from "../src/domain/history";
import {osmPlaces} from "../src/domain/place-adapters";
import {visitContext} from "../src/domain/personal-activity";
import type {Visit} from "../src/contracts/personal-insights";
import {daySchema,type HistorySource,type MonthlyInsight} from "../src/contracts/history";
const places=osmPlaces({elements:[{type:"node",id:1,lat:35,lon:136,tags:{name:"試験カフェ",amenity:"cafe"}},{type:"node",id:2,lat:35.001,lon:136.002,tags:{name:"試験書店",shop:"books"}}]});
function visit(id:string,at:string,place=0,minutes:number|null=60):Visit{const time=new Date(at).toISOString();return {id,userId:"A",placeId:places[place].id,enteredAt:time,exitedAt:new Date(Date.parse(time)+(minutes??0)*60000).toISOString(),durationMinutes:minutes,context:visitContext(time),source:"manual"};}
function source(visits:Visit[]):HistorySource{return {visits,places,points:[],months:[...new Set(visits.map(v=>japanDay(v.enteredAt).slice(0,7)))],days:visits.map(v=>japanDay(v.enteredAt)),firstVisits:Object.fromEntries(places.map(p=>[p.id,visits.filter(v=>v.placeId===p.id).map(v=>v.enteredAt).sort()[0]]).filter(([,v])=>v)),truncated:false};}
describe("History aggregation",()=>{
 it("handles empty and one visit without inventing GPS or missing stay duration",()=>{expect(aggregateHistory(source([]),"month","2026-09").empty).toBe(true);const s=source([visit("a","2026-09-08T12:00:00+09:00",0,null)]);const d=getDayJourney(s,"2026-09-08");expect(d.visits[0].periodMinutes).toBeNull();expect(d.route.kind).toBe("none");expect(getMonthlyHistorySummary(s,"2026-09")).toMatchObject({uniquePlaces:1,newPlaces:1,totalVisits:1,unknownDurationVisits:1,distanceMeters:null});});
 it("orders same-day visits, marks straight lines as visit order, keeps repeated visits",()=>{const s=source([visit("c","2026-09-08T15:00:00+09:00"),visit("a","2026-09-08T10:00:00+09:00"),visit("b","2026-09-08T12:00:00+09:00",1)]);const d=getDayJourney(s,"2026-09-08");expect(d.visits.map(v=>v.id)).toEqual(["a","b","c"]);expect(d.pins.map(p=>p.order)).toEqual([1,2,3]);expect(d.route.kind).toBe("visit_order");expect(getMonthlyHistorySummary(s,"2026-09")).toMatchObject({totalVisits:3,uniquePlaces:2,newPlaces:2,visitDays:1});});
 it("splits overnight duration across Japan months and preserves global first visit",()=>{const s=source([visit("overnight","2026-08-31T23:30:00+09:00",0,90),visit("again","2026-09-03T10:00:00+09:00")]);expect(getMonthlyHistorySummary(s,"2026-08").totalStayMinutes).toBe(30);expect(getMonthlyHistorySummary(s,"2026-09")).toMatchObject({totalStayMinutes:120,newPlaces:0,visitDays:2});expect(getDayJourney(s,"2026-09-01").visits[0].periodMinutes).toBe(60);expect(daySchema.safeParse("2026-02-30").success).toBe(false);expect(periodBounds("2026-09").start).toBe(Date.parse("2026-08-31T15:00:00Z"));});
 it("replay never includes later visits and new status is per month",()=>{const s=source([visit("a","2026-08-02T12:00:00+09:00"),visit("b","2026-09-02T12:00:00+09:00",1)]);expect(aggregateHistory(s,"replay","2026-08").replay.pins).toHaveLength(1);const r=aggregateHistory(s,"replay","2026-09").replay;expect(r.pins).toHaveLength(2);expect(r.newPlaceIds).toEqual([places[1].id]);});
 it("bounds large day payloads and keeps statistics independent",()=>{const s=source(Array.from({length:8000},(_,i)=>visit(String(i),"2026-09-08T12:00:00+09:00")));expect(getDayJourney(s,"2026-09-08").visits.length).toBeLessThanOrEqual(500);expect(getMonthlyHistorySummary(s,"2026-09").totalVisits).toBe(8000);});
 it("revision invalidates cache, actor scope and monthly AI failure remain safe",async()=>{const path=join(mkdtempSync(join(tmpdir(),"history-test-")),"test.sqlite"),personal=new PersonalStore(path),store=new HistoryStore(path);let bad=false,calls=0;const service=new HistoryService(store,{async generateMonthlyInsight(){calls++;if(bad)return {summary:123} as unknown as MonthlyInsight;return {title:"記録の変化",summary:"記録が増えています。",confidence:0.5};}},places);
  expect(service.get("A","month","2026-09").empty).toBe(true);personal.put("A","visit","1",visit("1","2026-09-08T12:00:00+09:00"));expect(service.get("A","month","2026-09").summary.totalVisits).toBe(1);expect(service.get("B","month","2026-09").empty).toBe(true);expect((await service.generateMonthlyInsight("A","2026-09")).summary.aiInsight?.confidence).toBe(0.5);await service.generateMonthlyInsight("A","2026-09");expect(calls).toBe(1);bad=true;personal.put("B","visit","2",{...visit("2","2026-09-08T12:00:00+09:00"),userId:"B"});const result=await service.generateMonthlyInsight("B","2026-09");expect(result.warning).toBeTruthy();expect(result.summary.totalVisits).toBe(1);expect(result.summary.aiInsight).toBeUndefined();});
});
